version: "3.8"

services:
  # Database service
  database:
    container_name: ml-challenge-database
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: transformer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: unless-stopped

  scheduler:
    image: ghcr.io/dask/dask:latest
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    image: ghcr.io/dask/dask-notebook:latest
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
  # Main backend application
  backend:
    container_name: ml-challenge-challenge-backend
    build:
      context: ${PWD}/backend/
      dockerfile: Dockerfile.development
    image: ml-challenge-challenge-backend
    ports:
      - "8000:8000"
    environment:
      BROKER_URL: redis://redis:6379
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_NAME: mlchellenge
    volumes:
      - ${PWD}/backend/:/home/user/backend/:delegated
      - ${PWD}/frontend/:/home/user/frontend/:delegated
    depends_on:
      - database
      - scheduler
      - worker
    restart: on-failure
